import { z } from 'zod';
import { LIMITS } from '../limits';

export const STORY_STATUSES = ['ongoing', 'completed', 'hiatus'] as const;
export const storyStatusSchema = z.enum(STORY_STATUSES);
export type StoryStatus = z.infer<typeof storyStatusSchema>;

export const STORY_VISIBILITIES = ['draft', 'published', 'hidden_by_mod'] as const;
export type StoryVisibility = (typeof STORY_VISIBILITIES)[number];

export const TAG_KINDS = ['genre', 'theme', 'warning'] as const;
export type TagKind = (typeof TAG_KINDS)[number];

/** Tag slugs are generated by `slugify`: lowercase ASCII words joined by `-`. */
export const tagSlugSchema = z
  .string()
  .max(60)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);

// NFC so the same title typed on different keyboards (composed vs. combining marks) is stored
// and counted the same way.
const storyTitleSchema = z
  .string()
  .trim()
  .normalize('NFC')
  .min(LIMITS.storyTitle.min)
  .max(LIMITS.storyTitle.max);

const storySynopsisSchema = z.string().trim().normalize('NFC').max(LIMITS.storySynopsisMax);

/** Extra tags besides the main one; the server resolves merged tags and counts the total. */
const storyTagsSchema = z.array(tagSlugSchema).max(LIMITS.storyTagsMax);

export const storyCreateSchema = z.object({
  title: storyTitleSchema,
  synopsis: storySynopsisSchema.default(''),
  /** Main tag (kind = genre). */
  mainTag: tagSlugSchema,
  tags: storyTagsSchema.default([]),
  isMature: z.boolean().default(false),
  isAiAssisted: z.boolean().default(false),
});

export type StoryCreateInput = z.output<typeof storyCreateSchema>;

/**
 * Declared separately instead of `storyCreateSchema.partial()`: defaults must never fill in fields
 * the author did not send. Tags are replaced as a set, so `mainTag` and `tags` travel together.
 */
export const storyUpdateSchema = z
  .object({
    title: storyTitleSchema.optional(),
    synopsis: storySynopsisSchema.optional(),
    mainTag: tagSlugSchema.optional(),
    tags: storyTagsSchema.optional(),
    isMature: z.boolean().optional(),
    isAiAssisted: z.boolean().optional(),
    status: storyStatusSchema.optional(),
  })
  .refine((input) => Object.values(input).some((value) => value !== undefined), {
    message: 'At least one field is required',
  })
  .refine((input) => (input.tags === undefined) === (input.mainTag === undefined), {
    message: 'mainTag and tags must be sent together',
    path: ['tags'],
  });

export type StoryUpdateInput = z.output<typeof storyUpdateSchema>;
