/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentPolicyRouteImport } from './routes/content-policy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthorsUsernameRouteImport } from './routes/authors.$username'
import { Route as RankingsIndexRouteImport } from './routes/rankings.index'
import { Route as RankingsPeriodRouteImport } from './routes/rankings.$period'
import { Route as SitemapPagesRouteImport } from './routes/sitemap/pages'
import { Route as TagsTagSlugRouteImport } from './routes/tags.$tagSlug'
import { Route as WriteIndexRouteImport } from './routes/write/index'
import { Route as SitemapChaptersPageRouteImport } from './routes/sitemap/chapters/$page'
import { Route as SitemapStoriesPageRouteImport } from './routes/sitemap/stories/$page'
import { Route as StoriesStoryKeyIndexRouteImport } from './routes/stories.$storyKey.index'
import { Route as StoriesStoryKeyChapterChar123numberChar125RouteImport } from './routes/stories.$storyKey.chapter-{$number}'
import { Route as WriteStoriesNewRouteImport } from './routes/write/stories/new'
import { Route as WriteStoriesPublicIdIndexRouteImport } from './routes/write/stories/$publicId/index'
import { Route as WriteStoriesPublicIdStatsRouteImport } from './routes/write/stories/$publicId/stats'
import { Route as WriteStoriesPublicIdChaptersNumberRouteImport } from './routes/write/stories/$publicId/chapters/$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentPolicyRoute = ContentPolicyRouteImport.update({
  id: '/content-policy',
  path: '/content-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsUsernameRoute = AuthorsUsernameRouteImport.update({
  id: '/authors/$username',
  path: '/authors/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsPeriodRoute = RankingsPeriodRouteImport.update({
  id: '/rankings/$period',
  path: '/rankings/$period',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesRoute = SitemapPagesRouteImport.update({
  id: '/sitemap/pages',
  path: '/sitemap/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagSlugRoute = TagsTagSlugRouteImport.update({
  id: '/tags/$tagSlug',
  path: '/tags/$tagSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIndexRoute = WriteIndexRouteImport.update({
  id: '/write/',
  path: '/write/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapChaptersPageRoute = SitemapChaptersPageRouteImport.update({
  id: '/sitemap/chapters/$page',
  path: '/sitemap/chapters/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStoriesPageRoute = SitemapStoriesPageRouteImport.update({
  id: '/sitemap/stories/$page',
  path: '/sitemap/stories/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryKeyIndexRoute = StoriesStoryKeyIndexRouteImport.update({
  id: '/stories/$storyKey/',
  path: '/stories/$storyKey/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryKeyChapterChar123numberChar125Route =
  StoriesStoryKeyChapterChar123numberChar125RouteImport.update({
    id: '/stories/$storyKey/chapter-{$number}',
    path: '/stories/$storyKey/chapter-{$number}',
    getParentRoute: () => rootRouteImport,
  } as any)
const WriteStoriesNewRoute = WriteStoriesNewRouteImport.update({
  id: '/write/stories/new',
  path: '/write/stories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteStoriesPublicIdIndexRoute =
  WriteStoriesPublicIdIndexRouteImport.update({
    id: '/write/stories/$publicId/',
    path: '/write/stories/$publicId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WriteStoriesPublicIdStatsRoute =
  WriteStoriesPublicIdStatsRouteImport.update({
    id: '/write/stories/$publicId/stats',
    path: '/write/stories/$publicId/stats',
    getParentRoute: () => rootRouteImport,
  } as any)
const WriteStoriesPublicIdChaptersNumberRoute =
  WriteStoriesPublicIdChaptersNumberRouteImport.update({
    id: '/write/stories/$publicId/chapters/$number',
    path: '/write/stories/$publicId/chapters/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content-policy': typeof ContentPolicyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/authors/$username': typeof AuthorsUsernameRoute
  '/rankings/$period': typeof RankingsPeriodRoute
  '/sitemap/pages': typeof SitemapPagesRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/rankings/': typeof RankingsIndexRoute
  '/write/': typeof WriteIndexRoute
  '/sitemap/chapters/$page': typeof SitemapChaptersPageRoute
  '/sitemap/stories/$page': typeof SitemapStoriesPageRoute
  '/stories/$storyKey/chapter-{$number}': typeof StoriesStoryKeyChapterChar123numberChar125Route
  '/write/stories/new': typeof WriteStoriesNewRoute
  '/stories/$storyKey/': typeof StoriesStoryKeyIndexRoute
  '/write/stories/$publicId/stats': typeof WriteStoriesPublicIdStatsRoute
  '/write/stories/$publicId/': typeof WriteStoriesPublicIdIndexRoute
  '/write/stories/$publicId/chapters/$number': typeof WriteStoriesPublicIdChaptersNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content-policy': typeof ContentPolicyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/authors/$username': typeof AuthorsUsernameRoute
  '/rankings/$period': typeof RankingsPeriodRoute
  '/sitemap/pages': typeof SitemapPagesRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/rankings': typeof RankingsIndexRoute
  '/write': typeof WriteIndexRoute
  '/sitemap/chapters/$page': typeof SitemapChaptersPageRoute
  '/sitemap/stories/$page': typeof SitemapStoriesPageRoute
  '/stories/$storyKey/chapter-{$number}': typeof StoriesStoryKeyChapterChar123numberChar125Route
  '/write/stories/new': typeof WriteStoriesNewRoute
  '/stories/$storyKey': typeof StoriesStoryKeyIndexRoute
  '/write/stories/$publicId/stats': typeof WriteStoriesPublicIdStatsRoute
  '/write/stories/$publicId': typeof WriteStoriesPublicIdIndexRoute
  '/write/stories/$publicId/chapters/$number': typeof WriteStoriesPublicIdChaptersNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content-policy': typeof ContentPolicyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/authors/$username': typeof AuthorsUsernameRoute
  '/rankings/$period': typeof RankingsPeriodRoute
  '/sitemap/pages': typeof SitemapPagesRoute
  '/tags/$tagSlug': typeof TagsTagSlugRoute
  '/rankings/': typeof RankingsIndexRoute
  '/write/': typeof WriteIndexRoute
  '/sitemap/chapters/$page': typeof SitemapChaptersPageRoute
  '/sitemap/stories/$page': typeof SitemapStoriesPageRoute
  '/stories/$storyKey/chapter-{$number}': typeof StoriesStoryKeyChapterChar123numberChar125Route
  '/write/stories/new': typeof WriteStoriesNewRoute
  '/stories/$storyKey/': typeof StoriesStoryKeyIndexRoute
  '/write/stories/$publicId/stats': typeof WriteStoriesPublicIdStatsRoute
  '/write/stories/$publicId/': typeof WriteStoriesPublicIdIndexRoute
  '/write/stories/$publicId/chapters/$number': typeof WriteStoriesPublicIdChaptersNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content-policy'
    | '/forgot-password'
    | '/library'
    | '/moderation'
    | '/notifications'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms'
    | '/api/$'
    | '/authors/$username'
    | '/rankings/$period'
    | '/sitemap/pages'
    | '/tags/$tagSlug'
    | '/rankings/'
    | '/write/'
    | '/sitemap/chapters/$page'
    | '/sitemap/stories/$page'
    | '/stories/$storyKey/chapter-{$number}'
    | '/write/stories/new'
    | '/stories/$storyKey/'
    | '/write/stories/$publicId/stats'
    | '/write/stories/$publicId/'
    | '/write/stories/$publicId/chapters/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content-policy'
    | '/forgot-password'
    | '/library'
    | '/moderation'
    | '/notifications'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms'
    | '/api/$'
    | '/authors/$username'
    | '/rankings/$period'
    | '/sitemap/pages'
    | '/tags/$tagSlug'
    | '/rankings'
    | '/write'
    | '/sitemap/chapters/$page'
    | '/sitemap/stories/$page'
    | '/stories/$storyKey/chapter-{$number}'
    | '/write/stories/new'
    | '/stories/$storyKey'
    | '/write/stories/$publicId/stats'
    | '/write/stories/$publicId'
    | '/write/stories/$publicId/chapters/$number'
  id:
    | '__root__'
    | '/'
    | '/content-policy'
    | '/forgot-password'
    | '/library'
    | '/moderation'
    | '/notifications'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms'
    | '/api/$'
    | '/authors/$username'
    | '/rankings/$period'
    | '/sitemap/pages'
    | '/tags/$tagSlug'
    | '/rankings/'
    | '/write/'
    | '/sitemap/chapters/$page'
    | '/sitemap/stories/$page'
    | '/stories/$storyKey/chapter-{$number}'
    | '/write/stories/new'
    | '/stories/$storyKey/'
    | '/write/stories/$publicId/stats'
    | '/write/stories/$publicId/'
    | '/write/stories/$publicId/chapters/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentPolicyRoute: typeof ContentPolicyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRoute
  ModerationRoute: typeof ModerationRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthorsUsernameRoute: typeof AuthorsUsernameRoute
  RankingsPeriodRoute: typeof RankingsPeriodRoute
  SitemapPagesRoute: typeof SitemapPagesRoute
  TagsTagSlugRoute: typeof TagsTagSlugRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  WriteIndexRoute: typeof WriteIndexRoute
  SitemapChaptersPageRoute: typeof SitemapChaptersPageRoute
  SitemapStoriesPageRoute: typeof SitemapStoriesPageRoute
  StoriesStoryKeyChapterChar123numberChar125Route: typeof StoriesStoryKeyChapterChar123numberChar125Route
  WriteStoriesNewRoute: typeof WriteStoriesNewRoute
  StoriesStoryKeyIndexRoute: typeof StoriesStoryKeyIndexRoute
  WriteStoriesPublicIdStatsRoute: typeof WriteStoriesPublicIdStatsRoute
  WriteStoriesPublicIdIndexRoute: typeof WriteStoriesPublicIdIndexRoute
  WriteStoriesPublicIdChaptersNumberRoute: typeof WriteStoriesPublicIdChaptersNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-policy': {
      id: '/content-policy'
      path: '/content-policy'
      fullPath: '/content-policy'
      preLoaderRoute: typeof ContentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$username': {
      id: '/authors/$username'
      path: '/authors/$username'
      fullPath: '/authors/$username'
      preLoaderRoute: typeof AuthorsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$period': {
      id: '/rankings/$period'
      path: '/rankings/$period'
      fullPath: '/rankings/$period'
      preLoaderRoute: typeof RankingsPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/pages': {
      id: '/sitemap/pages'
      path: '/sitemap/pages'
      fullPath: '/sitemap/pages'
      preLoaderRoute: typeof SitemapPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagSlug': {
      id: '/tags/$tagSlug'
      path: '/tags/$tagSlug'
      fullPath: '/tags/$tagSlug'
      preLoaderRoute: typeof TagsTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/': {
      id: '/write/'
      path: '/write'
      fullPath: '/write/'
      preLoaderRoute: typeof WriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/chapters/$page': {
      id: '/sitemap/chapters/$page'
      path: '/sitemap/chapters/$page'
      fullPath: '/sitemap/chapters/$page'
      preLoaderRoute: typeof SitemapChaptersPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/stories/$page': {
      id: '/sitemap/stories/$page'
      path: '/sitemap/stories/$page'
      fullPath: '/sitemap/stories/$page'
      preLoaderRoute: typeof SitemapStoriesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyKey/': {
      id: '/stories/$storyKey/'
      path: '/stories/$storyKey'
      fullPath: '/stories/$storyKey/'
      preLoaderRoute: typeof StoriesStoryKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyKey/chapter-{$number}': {
      id: '/stories/$storyKey/chapter-{$number}'
      path: '/stories/$storyKey/chapter-{$number}'
      fullPath: '/stories/$storyKey/chapter-{$number}'
      preLoaderRoute: typeof StoriesStoryKeyChapterChar123numberChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/stories/new': {
      id: '/write/stories/new'
      path: '/write/stories/new'
      fullPath: '/write/stories/new'
      preLoaderRoute: typeof WriteStoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/stories/$publicId/': {
      id: '/write/stories/$publicId/'
      path: '/write/stories/$publicId'
      fullPath: '/write/stories/$publicId/'
      preLoaderRoute: typeof WriteStoriesPublicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/stories/$publicId/stats': {
      id: '/write/stories/$publicId/stats'
      path: '/write/stories/$publicId/stats'
      fullPath: '/write/stories/$publicId/stats'
      preLoaderRoute: typeof WriteStoriesPublicIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/stories/$publicId/chapters/$number': {
      id: '/write/stories/$publicId/chapters/$number'
      path: '/write/stories/$publicId/chapters/$number'
      fullPath: '/write/stories/$publicId/chapters/$number'
      preLoaderRoute: typeof WriteStoriesPublicIdChaptersNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentPolicyRoute: ContentPolicyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRoute,
  ModerationRoute: ModerationRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthorsUsernameRoute: AuthorsUsernameRoute,
  RankingsPeriodRoute: RankingsPeriodRoute,
  SitemapPagesRoute: SitemapPagesRoute,
  TagsTagSlugRoute: TagsTagSlugRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  WriteIndexRoute: WriteIndexRoute,
  SitemapChaptersPageRoute: SitemapChaptersPageRoute,
  SitemapStoriesPageRoute: SitemapStoriesPageRoute,
  StoriesStoryKeyChapterChar123numberChar125Route:
    StoriesStoryKeyChapterChar123numberChar125Route,
  WriteStoriesNewRoute: WriteStoriesNewRoute,
  StoriesStoryKeyIndexRoute: StoriesStoryKeyIndexRoute,
  WriteStoriesPublicIdStatsRoute: WriteStoriesPublicIdStatsRoute,
  WriteStoriesPublicIdIndexRoute: WriteStoriesPublicIdIndexRoute,
  WriteStoriesPublicIdChaptersNumberRoute:
    WriteStoriesPublicIdChaptersNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
