/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as WriteIndexRouteImport } from './routes/write/index'
import { Route as WriteStoriesNewRouteImport } from './routes/write/stories/new'
import { Route as WriteStoriesPublicIdIndexRouteImport } from './routes/write/stories/$publicId/index'
import { Route as WriteStoriesPublicIdChaptersNumberRouteImport } from './routes/write/stories/$publicId/chapters/$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteIndexRoute = WriteIndexRouteImport.update({
  id: '/write/',
  path: '/write/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteStoriesNewRoute = WriteStoriesNewRouteImport.update({
  id: '/write/stories/new',
  path: '/write/stories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteStoriesPublicIdIndexRoute =
  WriteStoriesPublicIdIndexRouteImport.update({
    id: '/write/stories/$publicId/',
    path: '/write/stories/$publicId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WriteStoriesPublicIdChaptersNumberRoute =
  WriteStoriesPublicIdChaptersNumberRouteImport.update({
    id: '/write/stories/$publicId/chapters/$number',
    path: '/write/stories/$publicId/chapters/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/write/': typeof WriteIndexRoute
  '/write/stories/new': typeof WriteStoriesNewRoute
  '/write/stories/$publicId/': typeof WriteStoriesPublicIdIndexRoute
  '/write/stories/$publicId/chapters/$number': typeof WriteStoriesPublicIdChaptersNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/write': typeof WriteIndexRoute
  '/write/stories/new': typeof WriteStoriesNewRoute
  '/write/stories/$publicId': typeof WriteStoriesPublicIdIndexRoute
  '/write/stories/$publicId/chapters/$number': typeof WriteStoriesPublicIdChaptersNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/$': typeof ApiSplatRoute
  '/write/': typeof WriteIndexRoute
  '/write/stories/new': typeof WriteStoriesNewRoute
  '/write/stories/$publicId/': typeof WriteStoriesPublicIdIndexRoute
  '/write/stories/$publicId/chapters/$number': typeof WriteStoriesPublicIdChaptersNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/$'
    | '/write/'
    | '/write/stories/new'
    | '/write/stories/$publicId/'
    | '/write/stories/$publicId/chapters/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/$'
    | '/write'
    | '/write/stories/new'
    | '/write/stories/$publicId'
    | '/write/stories/$publicId/chapters/$number'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/$'
    | '/write/'
    | '/write/stories/new'
    | '/write/stories/$publicId/'
    | '/write/stories/$publicId/chapters/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiSplatRoute: typeof ApiSplatRoute
  WriteIndexRoute: typeof WriteIndexRoute
  WriteStoriesNewRoute: typeof WriteStoriesNewRoute
  WriteStoriesPublicIdIndexRoute: typeof WriteStoriesPublicIdIndexRoute
  WriteStoriesPublicIdChaptersNumberRoute: typeof WriteStoriesPublicIdChaptersNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/': {
      id: '/write/'
      path: '/write'
      fullPath: '/write/'
      preLoaderRoute: typeof WriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/stories/new': {
      id: '/write/stories/new'
      path: '/write/stories/new'
      fullPath: '/write/stories/new'
      preLoaderRoute: typeof WriteStoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/stories/$publicId/': {
      id: '/write/stories/$publicId/'
      path: '/write/stories/$publicId'
      fullPath: '/write/stories/$publicId/'
      preLoaderRoute: typeof WriteStoriesPublicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write/stories/$publicId/chapters/$number': {
      id: '/write/stories/$publicId/chapters/$number'
      path: '/write/stories/$publicId/chapters/$number'
      fullPath: '/write/stories/$publicId/chapters/$number'
      preLoaderRoute: typeof WriteStoriesPublicIdChaptersNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiSplatRoute: ApiSplatRoute,
  WriteIndexRoute: WriteIndexRoute,
  WriteStoriesNewRoute: WriteStoriesNewRoute,
  WriteStoriesPublicIdIndexRoute: WriteStoriesPublicIdIndexRoute,
  WriteStoriesPublicIdChaptersNumberRoute:
    WriteStoriesPublicIdChaptersNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
