import type { S3Env } from '@novel-hub/shared/env';
import { AwsClient } from 'aws4fetch';
import type { StoragePort } from './storage';

export interface S3Config {
  endpoint: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  region: string;
  publicUrl: string;
  /** MinIO needs path-style URLs (`https://host/bucket/key`). */
  forcePathStyle: boolean;
}

/** Every S3 request gives up after this long instead of hanging an upload request. */
const S3_TIMEOUT_MS = 10_000;

export function s3ConfigFromEnv(env: S3Env): S3Config {
  return {
    endpoint: env.S3_ENDPOINT,
    bucket: env.S3_BUCKET,
    accessKeyId: env.S3_ACCESS_KEY_ID,
    secretAccessKey: env.S3_SECRET_ACCESS_KEY,
    region: env.S3_REGION,
    publicUrl: env.S3_PUBLIC_URL,
    forcePathStyle: env.S3_FORCE_PATH_STYLE,
  };
}

function trimSlash(url: string): string {
  return url.replace(/\/+$/, '');
}

/**
 * S3 client over `fetch`, signed with SigV4 by `aws4fetch`. Keys are generated by the server
 * (`[a-z0-9/._-]`), so they need no URL encoding. Errors carry only the HTTP status: the response
 * body and the signed URL never reach logs or API responses.
 */
export function createS3Storage(cfg: S3Config, fetchImpl: typeof fetch = fetch): StoragePort {
  const client = new AwsClient({
    accessKeyId: cfg.accessKeyId,
    secretAccessKey: cfg.secretAccessKey,
    service: 's3',
    region: cfg.region,
  });
  const endpoint = new URL(trimSlash(cfg.endpoint));
  const objectUrl = (key: string) =>
    cfg.forcePathStyle
      ? `${endpoint.origin}${trimSlash(endpoint.pathname)}/${cfg.bucket}/${key}`
      : `${endpoint.protocol}//${cfg.bucket}.${endpoint.host}${trimSlash(endpoint.pathname)}/${key}`;
  const publicBase = trimSlash(cfg.publicUrl);

  async function send(method: 'PUT' | 'DELETE', key: string, init: RequestInit = {}) {
    const signed = await client.sign(objectUrl(key), { ...init, method });
    const res = await fetchImpl(signed, { signal: AbortSignal.timeout(S3_TIMEOUT_MS) });
    // Drain the body so the connection is released.
    await res.body?.cancel();
    return res;
  }

  return {
    async put(key, body, { contentType, cacheControl }) {
      const res = await send('PUT', key, {
        // DOM typings only accept views over a plain `ArrayBuffer`; sharp and `File.arrayBuffer()`
        // never hand out a `SharedArrayBuffer`.
        body: body as Uint8Array<ArrayBuffer>,
        headers: { 'Content-Type': contentType, 'Cache-Control': cacheControl },
      });
      if (!res.ok) throw new Error(`S3 PUT failed with status ${res.status}`);
    },
    async delete(key) {
      const res = await send('DELETE', key);
      if (!res.ok && res.status !== 404) {
        throw new Error(`S3 DELETE failed with status ${res.status}`);
      }
    },
    publicUrl: (key) => `${publicBase}/${key}`,
  };
}
