// Text bank for the demo seed: sample sentences per genre, randomly assembled into chapters.
// `{A}`, `{B}` are character names, `{P}` is a place. Original text, not taken from real novels.

export interface GenreBank {
  /** Main tag slug (kind = genre). */
  slug: string;
  names: string[];
  places: string[];
  titleHeads: string[];
  titleTails: string[];
  chapterTitles: string[];
  synopses: string[];
  sentences: string[];
}

/** Genre-neutral sentences mixed in so paragraphs read less uniformly. */
export const COMMON_SENTENCES = [
  'Một lúc lâu sau, không ai nói thêm lời nào.',
  '{A} hít sâu một hơi, cố giữ cho giọng mình bình thản.',
  'Gió lùa qua khe cửa, mang theo mùi đất ẩm sau cơn mưa.',
  'Có những chuyện chỉ cần nói ra một lần là đủ thay đổi tất cả.',
  '{B} khẽ gật đầu, ánh mắt lóe lên một tia khó đoán.',
  'Thời gian như chậm lại, từng nhịp tim nghe rõ mồn một.',
  'Trong lòng {A} dâng lên một cảm giác vừa quen thuộc vừa xa lạ.',
  'Phía xa, tiếng chuông vọng lại, đều đặn và lạnh lùng.',
  'Chẳng ai ngờ được rằng mọi chuyện lại bắt đầu từ một buổi chiều bình thường như thế.',
  '{B} quay đi, để lại sau lưng một khoảng lặng dài.',
  'Ánh đèn hắt lên tường những cái bóng chập chờn.',
  '{A} tự nhủ, lần này mình không được phép sai.',
];

export const GENRES: GenreBank[] = [
  {
    slug: 'tien-hiep',
    names: ['Lục Trần', 'Bạch Vân Khê', 'Tô Mộ', 'Hàn Lập Thu', 'Diệp Thanh Y', 'Cố Trường Ca'],
    places: ['Thanh Vân Tông', 'núi Vạn Kiếm', 'Linh Hư Cốc', 'Thiên Trì'],
    titleHeads: ['Vạn Cổ', 'Thiên Đạo', 'Cửu U', 'Huyền Thiên', 'Vô Tận', 'Thái Hư', 'Bất Diệt'],
    titleTails: ['Kiếm Tôn', 'Tiên Lộ', 'Đế Quân', 'Đạo Chủ', 'Trường Sinh', 'Tiên Đồ', 'Thần Ma'],
    chapterTitles: [
      'Phế linh căn',
      'Viên đan dược cuối cùng',
      'Trưởng lão ngoại môn',
      'Bí cảnh mở ra',
      'Một kiếm chém sơn hà',
      'Lôi kiếp',
      'Đan điền rạn nứt',
      'Tông môn đại bỉ',
      'Ma tu xuất hiện',
      'Trúc cơ',
      'Cổ thư không chữ',
      'Đêm trăng ở Thiên Trì',
    ],
    synopses: [
      'Bị trục xuất khỏi {P} vì linh căn hỗn tạp, {A} nhặt được một quyển cổ thư không chữ và bước lên con đường tu tiên ngược dòng.',
      '{A} chỉ muốn sống yên ổn ở {P}, cho đến khi một lần độ kiếp thất bại của người khác rơi trúng đầu mình.',
      'Ba nghìn năm trước {A} là đạo chủ, ba nghìn năm sau chỉ là đệ tử quét lá ở {P}. Lần này hắn sẽ đi một con đường khác.',
    ],
    sentences: [
      'Linh khí trong {P} dày đặc như sương sớm, chỉ cần hít một hơi cũng thấy kinh mạch ấm lên.',
      '{A} ngồi xếp bằng trên tảng đá xanh, dẫn từng sợi linh khí mỏng manh đi qua đan điền.',
      'Trưởng lão nhìn {A} rất lâu, rồi lắc đầu nói rằng linh căn này trăm năm khó thành đại đạo.',
      'Kiếm quang lóe lên giữa không trung, chém đôi tầng mây đang cuồn cuộn kéo tới.',
      '{B} phất tay áo, một luồng hàn khí lan ra khiến cả đại điện im phăng phắc.',
      'Viên đan dược trong lòng bàn tay {A} tỏa ra mùi thơm nhàn nhạt, màu sắc trong như ngọc.',
      'Đệ tử ngoại môn xì xào bàn tán, ai cũng nghĩ {A} chẳng trụ nổi qua vòng đầu.',
      'Lôi vân tụ lại trên đỉnh {P}, từng tia sét tím xé rách bầu trời đêm.',
      'Cổ thư mở ra, những dòng chữ vàng nhạt chậm rãi hiện lên rồi chìm vào thức hải của {A}.',
      '{B} cười nhạt, nói rằng tu tiên vốn là nghịch thiên, kẻ yếu thì không có tư cách oán trời.',
      'Kiếm ý lạnh buốt thấm qua da thịt, đau đến mức mồ hôi ướt đẫm áo, nhưng {A} không lùi.',
      'Trên đường về {P}, {A} gặp một lão nhân áo xám đang ngồi câu cá bên vực sâu không đáy.',
      'Tin đồn bí cảnh sắp mở lan khắp tu chân giới, các tông môn lớn đều phái người tới.',
      '{A} siết chặt chuôi kiếm gỗ đã mòn nhẵn, mỗi đường kiếm vẫn thẳng như ngày đầu.',
    ],
  },
  {
    slug: 'huyen-huyen',
    names: ['Thẩm Dạ', 'Lam Nguyệt', 'Mạc Bắc', 'Y Lăng', 'Tần Hạo', 'Phong Linh'],
    places: ['Đế quốc Thần Diệu', 'rừng Hắc Ám', 'học viện Tinh Thần', 'thành Lạc Nhật'],
    titleHeads: [
      'Thần Ấn',
      'Hồn Thú',
      'Tinh Hà',
      'Long Huyết',
      'Ma Pháp',
      'Huyết Mạch',
      'Vương Tọa',
    ],
    titleTails: [
      'Chí Tôn',
      'Thức Tỉnh',
      'Vương Quyền',
      'Truyền Thuyết',
      'Đại Lục',
      'Bá Chủ',
      'Phong Thần',
    ],
    chapterTitles: [
      'Nghi thức thức tỉnh',
      'Hồn thú cấp thấp nhất',
      'Kỳ thi nhập học',
      'Khu rừng cấm',
      'Long ngữ',
      'Huyết mạch thức tỉnh',
      'Đấu trường ngầm',
      'Giao kèo với ác ma',
      'Đêm huyết nguyệt',
      'Kẻ đứng sau tấm màn',
      'Vương tọa trống',
    ],
    synopses: [
      'Ngày thức tỉnh, {A} chỉ triệu hồi được một con mèo xám. Không ai biết đó là con cuối cùng của tộc rồng cổ.',
      'Ở {P}, huyết mạch quyết định số phận. {A} sinh ra không có huyết mạch, nên phải tự viết lấy số phận của mình.',
      'Bị đẩy xuống vực ở {P}, {A} tỉnh lại cùng một giọng nói tự xưng là vị thần đã bị lãng quên.',
    ],
    sentences: [
      'Ma pháp trận dưới chân {A} sáng lên từng vòng, những ký tự cổ xoay chầm chậm.',
      'Con hồn thú nhỏ cuộn tròn trong lòng {A}, đôi mắt vàng hé mở nhìn quanh đầy cảnh giác.',
      'Cả quảng trường ở {P} im lặng khi viên tinh thạch đo lường chỉ sáng lên một vạch mờ nhạt.',
      '{B} giơ tay, ngọn lửa xanh bùng lên thiêu rụi hàng cây trước mặt chỉ trong chớp mắt.',
      'Tiếng gầm trầm đục vang lên từ sâu trong rừng Hắc Ám, khiến lũ chim vỗ cánh bay tán loạn.',
      'Huyết mạch trong người {A} sôi trào, từng mạch máu như có lửa chạy qua.',
      'Giáo sư già nheo mắt, nói rằng đã ba trăm năm học viện chưa thấy hiện tượng như vậy.',
      'Trên bầu trời {P}, hai vầng trăng một đỏ một bạc từ từ tiến lại gần nhau.',
      '{B} đặt một đồng xu đen lên bàn, bảo rằng mọi giao kèo đều có giá của nó.',
      '{A} nhìn vết ấn mới hiện trên mu bàn tay, không biết nên vui hay nên sợ.',
      'Đội kỵ sĩ áo bạc phi ngựa qua cổng thành, cờ hiệu đế quốc bay phần phật trong gió.',
      'Long ngữ phát ra từ miệng {A} trầm thấp và cổ xưa, như vọng lên từ đáy đất.',
    ],
  },
  {
    slug: 'do-thi',
    names: ['Trần Minh', 'Ngọc Hân', 'Lê Quân', 'Vy Anh', 'Hoàng Phúc', 'Bảo Trâm'],
    places: ['quận Tư', 'phố Tạ Hiện', 'cầu Ánh Sao', 'chợ Bến Thành'],
    titleHeads: [
      'Đêm Trắng',
      'Thành Phố',
      'Ngã Tư',
      'Mùa Mưa',
      'Tầng Thượng',
      'Hẻm Nhỏ',
      'Ánh Đèn',
    ],
    titleTails: [
      'Không Ngủ',
      'Ở Sài Gòn',
      'Của Những Kẻ Lạc',
      'Cuối Cùng',
      'Phố Cũ',
      'Tháng Mười',
      'Và Em',
    ],
    chapterTitles: [
      'Cuốc xe ba giờ sáng',
      'Phong bì dán kín',
      'Quán cà phê vỉa hè',
      'Người hàng xóm mới',
      'Hợp đồng thứ hai',
      'Mưa ở quận Tư',
      'Cuộc gọi nhỡ',
      'Sân thượng',
      'Món nợ cũ',
      'Bình minh trên cầu',
    ],
    synopses: [
      'Một tài xế chạy xe đêm ở {P} nhận cuốc khách lạ, và chiếc phong bì bị bỏ quên kéo anh vào thế giới ngầm của thành phố.',
      '{A} bỏ việc văn phòng, mở một tiệm sửa đồ cũ ở {P}. Mỗi món đồ khách mang tới lại kèm theo một câu chuyện chưa kể hết.',
      'Sau mười năm biệt tích, {A} trở về {P} với một cái tên mới và một danh sách những người cần gặp lại.',
    ],
    sentences: [
      'Thành phố ba giờ sáng không ngủ hẳn, chỉ thiu thiu như người mệt tựa đầu vào cửa kính xe buýt.',
      '{A} đứng dưới mái hiên tiệm tạp hóa đã đóng cửa, điếu thuốc trên tay cháy gần hết.',
      'Bên kia đường, quán cà phê vỉa hè ở {P} vẫn sáng đèn, vài người đàn ông ngồi im lặng.',
      'Điện thoại rung lên lần thứ ba, màn hình hiện một số lạ không lưu tên.',
      '{B} đẩy ly cà phê sữa đá sang, bảo rằng ở đây ai cũng có một món nợ chưa trả.',
      'Chiếc xe máy không biển số bám theo, giữ khoảng cách vừa đủ để không bị chú ý.',
      'Mưa đổ xuống {P} như trút, nước dâng ngập nửa bánh xe chỉ trong vài phút.',
      '{A} rẽ vào con hẻm nhỏ quen thuộc, nơi có lối thoát ra đường lớn mà ít ai biết.',
      'Căn phòng trọ mười hai mét vuông chất đầy thùng giấy, mùi ẩm mốc lẫn mùi mì gói.',
      '{B} cười, nói rằng thành phố này không sợ bóng tối, chỉ sợ những gì bóng tối mang theo khi trời sáng.',
      'Tiếng còi xe, tiếng rao đêm và tiếng nhạc từ quán nhậu đầu hẻm trộn vào nhau thành một thứ âm thanh rất riêng.',
      'Trên sân thượng chung cư cũ, {A} nhìn xuống những dòng đèn xe chảy không ngừng.',
    ],
  },
  {
    slug: 'ngon-tinh',
    names: ['Hạ Vy', 'Cố Thần', 'An Nhiên', 'Lục Diễn', 'Tô Uyển', 'Kỷ Hàng'],
    places: [
      'thị trấn ven biển',
      'tiệm hoa đầu ngõ',
      'thư viện thành phố',
      'trường cấp ba Hướng Dương',
    ],
    titleHeads: ['Gió Mùa', 'Năm Ấy', 'Mùa Hạ', 'Ánh Trăng', 'Lời Hứa', 'Cánh Diều', 'Thanh Xuân'],
    titleTails: ['Có Em', 'Không Quên', 'Đến Muộn', 'Và Anh', 'Dịu Dàng', 'Bên Hồ', 'Rực Rỡ'],
    chapterTitles: [
      'Gặp lại sau mười năm',
      'Chiếc ô màu xanh',
      'Bức thư chưa gửi',
      'Lời tỏ tình hụt',
      'Buổi hẹn đầu tiên',
      'Hiểu lầm',
      'Mùa hoa phượng',
      'Người cũ',
      'Ở lại',
      'Nắng sau mưa',
    ],
    synopses: [
      'Mười năm sau ngày tốt nghiệp, {A} gặp lại {B} ở {P}, người từng hứa sẽ quay về nhưng chưa bao giờ trở lại.',
      '{A} mở {P} để quên một người. Người đó lại trở thành khách quen ghé mua một bó cúc trắng mỗi sáng thứ bảy.',
      'Một bản hợp đồng hôn nhân ba tháng, hai con người không tin vào tình yêu, và một mùa hè dài hơn dự tính.',
    ],
    sentences: [
      '{A} đứng lặng trước cửa {P}, tim đập nhanh đến mức tưởng như người khác cũng nghe thấy.',
      '{B} vẫn như năm ấy, áo sơ mi trắng, tay áo xắn lên, nụ cười nhàn nhạt mà ấm áp.',
      'Cơn mưa chiều tới bất chợt, chiếc ô màu xanh được nghiêng hẳn về phía {A}.',
      'Có những câu nói giữ trong lòng mười năm, đến lúc gặp lại vẫn không thốt ra được.',
      '{A} cúi đầu khuấy ly trà sữa đã tan hết đá, giả vờ như không để ý ánh mắt bên cạnh.',
      'Trong ngăn kéo vẫn còn bức thư viết tay chưa từng gửi, giấy đã ngả màu vàng nhạt.',
      '{B} khẽ nói, giọng trầm thấp, rằng năm đó không phải anh không muốn quay về.',
      'Hoa phượng đỏ rực sân trường, tiếng ve kêu như muốn kéo dài mãi mùa hè cuối cùng.',
      'Ngoài cửa sổ, ánh trăng rọi xuống mặt hồ, lấp lánh như ai đó rắc đầy vụn bạc.',
      '{A} bật cười, nhận ra mình đã giận một người suốt bao năm chỉ vì một hiểu lầm nhỏ.',
      'Bàn tay {B} chạm nhẹ vào tay {A}, rồi rất tự nhiên, không ai rút về.',
      'Gió biển thổi tung mái tóc, mang theo vị mặn và một chút gì đó rất giống hạnh phúc.',
    ],
  },
  {
    slug: 'kiem-hiep',
    names: ['Tiêu Dao', 'Lãnh Sương', 'Đoạn Phong', 'Mộ Dung Tuyết', 'Lý Tầm', 'Hoa Mãn Lâu'],
    places: ['Giang Nam', 'Võ Đang sơn', 'Lạc Dương thành', 'khách điếm Long Môn'],
    titleHeads: [
      'Giang Hồ',
      'Đao Kiếm',
      'Phong Vân',
      'Nhất Kiếm',
      'Huyết Ảnh',
      'Cô Kiếm',
      'Tuyết Sơn',
    ],
    titleTails: ['Dạ Hành', 'Phi Hồ', 'Tình Thù', 'Lãng Khách', 'Vô Song', 'Hành', 'Biệt Truyện'],
    chapterTitles: [
      'Khách điếm giữa sa mạc',
      'Thanh kiếm gãy',
      'Huyết thư',
      'Đêm mưa Giang Nam',
      'Võ lâm đại hội',
      'Ân oán ba mươi năm',
      'Một chén rượu tiễn biệt',
      'Ám khí tẩm độc',
      'Tuyết rơi trên Võ Đang',
      'Giang hồ hẹn gặp lại',
    ],
    synopses: [
      'Ba mươi năm trước, một đêm mưa ở {P} đã chôn vùi cả một môn phái. {A} mang thanh kiếm gãy đi tìm người còn sống sót cuối cùng.',
      '{A} chỉ là tiểu nhị ở {P}, cho đến khi một vị khách trọ để lại cuốn bí kíp và một món nợ máu.',
      'Giang hồ đồn rằng {A} đã chết dưới chân Võ Đang. Mười năm sau, một kiếm khách đeo mặt nạ xuất hiện ở {P}.',
    ],
    sentences: [
      'Khách điếm ở {P} tối om, chỉ còn một ngọn đèn dầu leo lét trên quầy.',
      '{A} đặt thanh kiếm gãy lên bàn, rót một chén rượu nhạt, chậm rãi uống cạn.',
      'Tiếng vó ngựa dồn dập ngoài cổng, bụi cát cuộn lên mù mịt cả con đường.',
      '{B} rút kiếm, lưỡi kiếm sáng như nước thu, ánh lên một đường lạnh lẽo.',
      'Giang hồ hiểm ác, lòng người còn hiểm hơn, câu ấy sư phụ đã dặn {A} không biết bao nhiêu lần.',
      'Ám khí xé gió lao tới, {A} nghiêng người né, ba mũi châm cắm phập vào cột gỗ sau lưng.',
      'Mưa Giang Nam dai dẳng, rơi xuống mái ngói rêu phong thành những chuỗi âm thanh buồn bã.',
      '{B} cười dài, nói rằng ân oán ba mươi năm, hôm nay nên có một kết cục.',
      'Hai bóng người giao đấu trên mái nhà, kiếm khí quét qua khiến ngói vỡ rơi lả tả.',
      '{A} nhớ lại đêm ấy, lửa cháy đỏ trời, tiếng kêu khóc vang khắp sơn môn.',
      'Một chén rượu tiễn biệt, không cần nhiều lời, giang hồ rộng lớn, ắt có ngày gặp lại.',
      'Trên đỉnh Võ Đang, tuyết phủ trắng xóa, chỉ có tiếng chuông chiều vọng xuống thung lũng.',
    ],
  },
  {
    slug: 'khoa-huyen',
    names: ['Kha Nguyên', 'Mira Trần', 'Đặng Vũ', 'Linh K-7', 'Quang Hải', 'Tuệ An'],
    places: ['trạm Hải Vương', 'tàu Tinh Vân', 'thành phố mái vòm số 3', 'vành đai tiểu hành tinh'],
    titleHeads: ['Tín Hiệu', 'Hành Tinh', 'Kỷ Nguyên', 'Tọa Độ', 'Quỹ Đạo', 'Bản Sao', 'Chân Trời'],
    titleTails: [
      'Cuối Cùng',
      'Thứ Chín',
      'Băng Giá',
      'Lặng Im',
      'Không Người',
      'Sau Đại Dịch',
      'Số 0',
    ],
    chapterTitles: [
      'Tín hiệu từ sao Hải Vương',
      'Ngủ đông',
      'Lỗi hệ thống',
      'Trí tuệ nhân tạo thức tỉnh',
      'Mái vòm nứt',
      'Bản đồ sao',
      'Người thứ mười ba',
      'Hố đen',
      'Ký ức nhân bản',
      'Trở về Trái Đất',
    ],
    synopses: [
      'Năm 2189, {P} nhận được một tín hiệu lặp lại mỗi 47 phút. {A} là người duy nhất giải mã được nó, và hối hận ngay sau đó.',
      'Tỉnh dậy sau giấc ngủ đông trên {P}, {A} phát hiện phi hành đoàn đã già đi ba mươi năm, còn mình thì không.',
      'Ở {P}, mỗi người được cấp một bản sao dự phòng. {A} vừa gặp bản sao của mình, và nó không muốn trả lại cuộc đời.',
    ],
    sentences: [
      'Màn hình điều khiển trên {P} nhấp nháy đỏ, tiếng cảnh báo vang lên đều đặn.',
      '{A} gõ nhanh dãy lệnh, những dòng mã xanh lục chạy dọc màn hình như thác nước.',
      'Ngoài ô kính, sao Hải Vương xanh thẫm lơ lửng, lạnh lẽo và im lặng tuyệt đối.',
      'Giọng nói tổng hợp của hệ thống trả lời chậm hơn thường lệ nửa giây.',
      '{B} lắc đầu, bảo rằng tín hiệu này không thể là tự nhiên, nó quá đều đặn.',
      'Buồng ngủ đông mở ra, hơi lạnh trắng xóa tràn ra sàn kim loại.',
      'Bản đồ sao ba chiều xoay chậm giữa phòng, một điểm sáng lạ nằm ngoài mọi tọa độ đã biết.',
      '{A} nhìn đồng hồ đếm ngược, còn bốn mươi bảy phút trước khi tín hiệu lặp lại.',
      'Ở thành phố mái vòm, bầu trời là một màn hình khổng lồ chiếu cảnh bình minh nhân tạo.',
      '{B} chạm vào bảng điều khiển, hàng nghìn dòng nhật ký cũ hiện lên, có những dòng mang tên {A}.',
      'Tàu rung lên dữ dội khi đi qua vành đai tiểu hành tinh, đèn trong khoang chập chờn.',
      'Không ai trên trạm còn nhớ lần cuối nhận được liên lạc từ Trái Đất là khi nào.',
    ],
  },
  {
    slug: 'kinh-di',
    names: ['Thạch Lam', 'Bà Năm', 'Khải', 'Mai Thảo', 'Ông Sáu', 'Nhã Uyên'],
    places: ['làng Đồng Mả', 'căn nhà số 13', 'bệnh viện bỏ hoang', 'giếng cổ sau đình'],
    titleHeads: ['Tiếng Gõ', 'Bóng Đêm', 'Căn Nhà', 'Làng', 'Giếng Cổ', 'Gương Vỡ', 'Hồi Chuông'],
    titleTails: ['Lúc Nửa Đêm', 'Số 13', 'Không Tên', 'Ma Ám', 'Cuối Ngõ', 'Thứ Bảy', 'Dưới Nước'],
    chapterTitles: [
      'Tiếng gõ cửa lúc nửa đêm',
      'Căn phòng khóa trái',
      'Bức ảnh cũ',
      'Người không có bóng',
      'Đêm rằm tháng bảy',
      'Giếng cổ',
      'Tiếng hát trong tường',
      'Gương',
      'Lá bùa đỏ',
      'Người cuối cùng',
    ],
    synopses: [
      'Chuyển về {P} để trốn nợ, {A} không biết rằng người thuê trước đều rời đi đúng vào đêm thứ bảy.',
      'Cả {P} có một luật bất thành văn: nghe tiếng gõ cửa sau nửa đêm thì không được trả lời. {A} đã quên mất điều đó.',
      'Nhóm bạn của {A} vào {P} quay video kiếm view. Chỉ có đoạn phim là trở ra.',
    ],
    sentences: [
      'Tiếng gõ cửa vang lên ba lần, chậm rãi, đều đặn, đúng lúc đồng hồ chỉ mười hai giờ.',
      '{A} nín thở, nhìn qua khe cửa, nhưng ngoài hành lang chỉ có bóng tối đặc quánh.',
      'Ở {P}, người già vẫn dặn con cháu không được soi gương sau khi trời tối.',
      'Mùi nhang trầm thoang thoảng dù trong nhà chẳng ai thắp nhang.',
      '{B} kể rằng người thuê trước cũng nghe thấy tiếng hát trong tường, rồi một sáng biến mất.',
      'Bức ảnh cũ trên bàn thờ, người đàn ông trong ảnh dường như đã quay mặt sang hướng khác.',
      'Nước trong giếng cổ đen ngòm, không phản chiếu nổi ánh trăng trên đầu.',
      '{A} bật đèn pin, vệt sáng run run quét qua những bức tường loang lổ vết ẩm.',
      'Có tiếng bước chân trên gác, dù cả căn nhà chỉ còn mình {A}.',
      '{B} dán lá bùa đỏ lên khung cửa, tay run đến mức suýt làm rơi.',
      'Đêm rằm tháng bảy, cả {P} im phăng phắc, đến tiếng chó sủa cũng không còn.',
      'Trong gương, phía sau lưng {A}, có ai đó đang mỉm cười.',
    ],
  },
  {
    slug: 'trinh-tham',
    names: ['Thanh Tra Lâm', 'Hải Đăng', 'Diệu Linh', 'Bác sĩ Khang', 'Phương Nam', 'Trung úy Tín'],
    places: ['biệt thự trên đồi', 'tòa soạn báo cũ', 'ga tàu Hàng Cỏ', 'khách sạn Bạch Mã'],
    titleHeads: ['Hồ Sơ', 'Án Mạng', 'Mật Mã', 'Nhân Chứng', 'Vụ Án', 'Dấu Vết', 'Lời Khai'],
    titleTails: [
      'Mùa Đông',
      'Thứ Bảy',
      'Trên Tàu',
      'Câm Lặng',
      'Bị Lãng Quên',
      'Cuối Cùng',
      'Màu Đỏ',
    ],
    chapterTitles: [
      'Thi thể trong phòng kín',
      'Nhân chứng duy nhất',
      'Chiếc đồng hồ dừng',
      'Lá thư nặc danh',
      'Bằng chứng ngoại phạm',
      'Kẻ thứ ba',
      'Mật mã trên tường',
      'Hồ sơ năm 1998',
      'Lời khai mâu thuẫn',
      'Sự thật',
    ],
    synopses: [
      'Một thi thể trong căn phòng khóa trái ở {P}, bảy người có mặt, và ai cũng có bằng chứng ngoại phạm hoàn hảo.',
      '{A} là phóng viên ở {P}, nhận được lá thư nặc danh hé lộ vụ án đã bị chôn vùi hai mươi năm.',
      'Chuyến tàu đêm rời {P} với mười hai hành khách. Đến sáng, chỉ còn mười một người.',
    ],
    sentences: [
      '{A} cúi xuống quan sát thi thể, ghi nhận vết bầm tím mờ trên cổ tay trái.',
      'Căn phòng khóa trái từ bên trong, chìa khóa vẫn nằm trong túi áo nạn nhân.',
      'Chiếc đồng hồ treo tường dừng ở mười giờ mười bảy phút, kim giây gãy đôi.',
      '{B} đưa ra bằng chứng ngoại phạm trôi chảy đến mức đáng ngờ.',
      'Ở {P}, mọi người đều nói không nghe thấy gì, nhưng không ai dám nhìn thẳng vào mắt {A}.',
      'Lá thư nặc danh viết bằng mực tím, nét chữ nghiêng như cố tình che giấu.',
      '{A} trải hồ sơ cũ lên bàn, những tấm ảnh đen trắng đã ố vàng theo năm tháng.',
      'Dấu giày bùn dừng lại giữa hành lang, như thể người đó đã biến mất vào không khí.',
      '{B} châm thuốc, nói rằng mỗi lời khai đều có một phần thật, vấn đề là phần nào.',
      'Mảnh giấy nhỏ dưới gầm giường ghi một dãy số, nhìn qua như số điện thoại nhưng thiếu một chữ số.',
      '{A} nhắm mắt, sắp xếp lại từng mốc thời gian trong đầu, và nhận ra có hai mươi phút không ai giải thích được.',
      'Mưa bắt đầu rơi, xóa dần những dấu vết cuối cùng trên con đường dẫn ra {P}.',
    ],
  },
];

export const AUTHOR_NOTES = [
  'Cảm ơn mọi người đã đọc tới đây, chương sau sẽ dài hơn một chút.',
  'Tuần này mình bận, có thể ra chương chậm vài ngày. Mong mọi người thông cảm.',
  'Chương này viết đi viết lại ba lần mới ưng. Có góp ý gì cứ để lại bình luận nhé.',
  'Ai đoán được kẻ đứng sau thì mình xin bái phục.',
  'Cảm ơn bạn đã báo lỗi chính tả ở chương trước, mình đã sửa rồi.',
];
